apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../common/argo-cd/argo-repo.yaml
  - ../../common/argo-cd/argo-namespace.yaml
  - ../../common/argo-cd/argo-release.yaml
patchesStrategicMerge:
  - argo-values.yaml