apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx
  namespace: cluster-config
spec:
  values:
    controller:
      service:
        annotations:
          metallb.universe.tf/loadBalancerIPs: "192.168.0.179"