apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
secretGenerator:
  - name: cacerts
    files:
      - ca-cert.pem
      - ca-key.pem
      - root-cert.pem
      - cert-chain.pem
generatorOptions:
  disableNameSuffixHash: true