apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: cluster-config
spec:
  targetNamespace: istio-system
  releaseName: istiod
  chart:
    spec:
      chart: istiod
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: cluster-config
      version: "1.25.0"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    global:
      meshID: multimesh