apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx
  namespace: cluster-config
spec:
  targetNamespace: nginx-ingress
  releaseName: nginx-ingress-controller
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: nginx-ingress
        namespace: cluster-config
      #version: "9.x"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    # global:
    #   image:
    #     registry: acr
    controller:
      ingressClassResource:
        default: true
      resources:
        requests:
          cpu: 100m
          memory: 90Mi
        limits:
          cpu: 200m
          memory: 200Mi
    defaultBackend:
      resources:
        requests:
          cpu: 100m
          memory: 90Mi
        limits:
          cpu: 200m
          memory: 200Mi
      serviceAccount:
        create: false
    ingressClassResource:
      name: nginx