apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: cluster-config
spec:
  values:
    global:
      meshID: multimesh
      multiCluster:
        clusterName: onprem-2
      network: onprem2
