apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../common/nginx/nginx-repo.yaml
  - ../../common/nginx/nginx-namespace.yaml
  - ../../common/nginx/nginx-release.yaml
patchesStrategicMerge:
  - nginx-values.yaml