apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../common/istio/istio-base-release.yaml
  - ../../common/istio/istio-d-release.yaml
  - ../../common/istio/istio-ew-gateway-release.yaml
patchesStrategicMerge:
  - istio-d-values.yaml
  - istio-gateway-values.yaml